### CREATE GOAL (only required fileds)
POST localhost:8080/api/v1/user/goals
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JieSIsImV4cCI6MTYzNjU3ODAwMH0.kdl1dck7Du5Z3GyilgEXA8Ujb964iBWBtFHdYftrcxB7AjAxwY8Bt2AQKRLn2FlTqDBfGvqrBpkvB839WhL94w
Content-Type: application/json

{
  "sphereUuid": "e188e241-8ab1-4edf-b6da-cdd81db6f3af",
  "name": "Цель номер два"
}

### CREATE GOAL (all fields)
POST localhost:8080/api/v1/user/goals
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JieSIsImV4cCI6MTYzNjU3ODAwMH0.kdl1dck7Du5Z3GyilgEXA8Ujb964iBWBtFHdYftrcxB7AjAxwY8Bt2AQKRLn2FlTqDBfGvqrBpkvB839WhL94w
Content-Type: application/json

{
  "sphereUuid": "2fb69ffd-bdf5-4ccb-ac64-dd0a76b5892e",
  "name": "Цель номер три",
  "targetDate": "2021-07-11T05:05:34.844Z",
  "description": "Сделать это и это для того и того",
  "backgroundColor": "#ff00aa"
}

### GET GOAL WITH STEPS
GET localhost:8080/api/v1/user/goals/1eb2a538-ef67-405e-b0a6-4b4942db19b1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JieSIsImV4cCI6MTYzNzAxMDAwMH0.LkDjT2xDweMXU_G3EbLVaf9iLpQpa8h3QwL7ltmsJg3k9vqNuG5OPv_pSsxwCVfKOMf9PFX4ZtFDJ827K7TTgA

### MODIFY
PUT localhost:8080/api/v1/user/goals
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JieSIsImV4cCI6MTYzNzAxMDAwMH0.LkDjT2xDweMXU_G3EbLVaf9iLpQpa8h3QwL7ltmsJg3k9vqNuG5OPv_pSsxwCVfKOMf9PFX4ZtFDJ827K7TTgA
Content-Type: application/json

{
  "uuid": "1eb2a538-ef67-405e-b0a6-4b4942db19b1",
  "targetDate": "2023-02-02T02:02:02.844Z",
  "name": "Цель номер пять",
  "description": "Описание",
  "backgroundColor": "#ff0033"
}


### CHANGE FINISHED
PUT localhost:8080/api/v1/user/goals/finish
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JieSIsImV4cCI6MTYzNzAxMDAwMH0.LkDjT2xDweMXU_G3EbLVaf9iLpQpa8h3QwL7ltmsJg3k9vqNuG5OPv_pSsxwCVfKOMf9PFX4ZtFDJ827K7TTgA
Content-Type: application/json

{
  "uuid": "1eb2a538-ef67-405e-b0a6-4b4942db19b1",
  "finished": true
}

###