### РЕГИСТРАЦИЯ
POST localhost:8080/api/v1/registration
Content-Type: application/json

{
"login": "bobby",
"password": "qwerty"
}

### АВТОРИЗАЦИЯ
POST localhost:8080/api/v1/auth
Content-Type: application/json

{
  "login": "bobby",
  "password": "qwerty"
}


###