### РЕГИСТРАЦИЯ
POST localhost:8080/api/v1/registration
Content-Type: application/json

{
"login": "bob",
"password": "qwerty"
}

### АВТОРИЗАЦИЯ
POST localhost:8080/api/v1/auth
Content-Type: application/json

{
  "login": "bob",
  "password": "qwerty"
}

###
GET localhost:8080/api/v1/user/spheres
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2IiLCJleHAiOjE2MjYwMzcyMDB9.Iw2BOdIGn5nF1T6stUWr0FPko2qFl_YNvuvCMhFVGWkSjsv1jCXlSgXT7M4YyqdmHPAZonnLio1Kqa1TelJXWQ

### CREATE SPHERE
POST localhost:8080/api/v1/user/spheres
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2IiLCJleHAiOjE2MjYwMzcyMDB9.Iw2BOdIGn5nF1T6stUWr0FPko2qFl_YNvuvCMhFVGWkSjsv1jCXlSgXT7M4YyqdmHPAZonnLio1Kqa1TelJXWQ
Content-Type: application/json

{
  "name": "Сфера 1",
  "backgroundColor": "#ff0000"
}

###