INSERT INTO roles_settings (tech_name, value, type, role_name)
VALUES
('USER_MAX_NUMBER_SPHERES', '5', 'INTEGER', 'ROLE_USER'),
('USER_MAX_NUMBER_GOALS', '10', 'INTEGER', 'ROLE_USER'),
('USER_MAX_NUMBER_STEPS', '10', 'INTEGER', 'ROLE_USER'),
('PREMIUM_USER_MAX_NUMBER_SPHERES', '12', 'INTEGER', 'ROLE_PREMIUM'),
('PREMIUM_USER_MAX_NUMBER_STEPS', '20', 'INTEGER', 'ROLE_PREMIUM'),
('PREMIUM_USER_MAX_NUMBER_STEPS', '20', 'INTEGER', 'ROLE_PREMIUM');